# Generated by Django 3.2.13 on 2022-05-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
